CREATE USER holedo_crm WITH PASSWORD 'local-holedo-crm-password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT ON DATABASE holedo_crm TO holedo_crm;
GRANT USAGE, CREATE ON SCHEMA public TO holedo_crm;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO holedo_crm;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO holedo_crm;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO holedo_crm;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO holedo_crm;
