CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE crm_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  keycloak_subject TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  platform_admin BOOLEAN NOT NULL DEFAULT FALSE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE crm_workspaces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_type TEXT NOT NULL CHECK (workspace_type IN ('personal', 'company')),
  name TEXT NOT NULL,
  owner_user_id UUID NOT NULL REFERENCES crm_users(id) ON DELETE RESTRICT,
  subscription_state TEXT NOT NULL DEFAULT 'active'
    CHECK (subscription_state IN ('active', 'grace', 'suspended', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id, workspace_type)
);

CREATE UNIQUE INDEX crm_one_personal_workspace_per_owner
  ON crm_workspaces (owner_user_id) WHERE workspace_type = 'personal';

CREATE TABLE crm_workspace_members (
  workspace_id UUID NOT NULL,
  workspace_type TEXT NOT NULL CHECK (workspace_type IN ('personal', 'company')),
  user_id UUID NOT NULL REFERENCES crm_users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('owner', 'administrator', 'editor', 'viewer')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (workspace_id, user_id),
  FOREIGN KEY (workspace_id, workspace_type)
    REFERENCES crm_workspaces(id, workspace_type) ON DELETE CASCADE
);

CREATE UNIQUE INDEX crm_one_company_membership_per_user
  ON crm_workspace_members (user_id)
  WHERE workspace_type = 'company' AND status IN ('active', 'suspended');

CREATE INDEX crm_workspace_members_user_idx
  ON crm_workspace_members (user_id, status);

CREATE TABLE crm_workspace_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('administrator', 'editor', 'viewer')),
  token_hash TEXT UNIQUE,
  invited_by_user_id UUID NOT NULL REFERENCES crm_users(id) ON DELETE RESTRICT,
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX crm_open_invitation_per_company_email
  ON crm_workspace_invitations (workspace_id, lower(email))
  WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE TABLE crm_oidc_flows (
  token_hash TEXT PRIMARY KEY,
  state TEXT NOT NULL,
  nonce TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  return_to TEXT NOT NULL DEFAULT '/',
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX crm_oidc_flows_expiry_idx ON crm_oidc_flows (expires_at);

CREATE TABLE crm_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES crm_users(id) ON DELETE CASCADE,
  active_workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  keycloak_session_id TEXT,
  refresh_token_encrypted TEXT,
  id_token_encrypted TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX crm_sessions_user_idx ON crm_sessions (user_id);
CREATE INDEX crm_sessions_keycloak_session_idx ON crm_sessions (keycloak_session_id);
CREATE INDEX crm_sessions_expiry_idx ON crm_sessions (expires_at);

CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  crm_user_id UUID REFERENCES crm_users(id) ON DELETE SET NULL,
  first_name TEXT NOT NULL DEFAULT 'Pending',
  last_name TEXT NOT NULL DEFAULT 'Pending',
  email TEXT NOT NULL,
  administrator BOOLEAN NOT NULL DEFAULT FALSE,
  avatar JSONB,
  disabled BOOLEAN NOT NULL DEFAULT FALSE,
  secondary_emails JSONB NOT NULL DEFAULT '[]'::JSONB,
  UNIQUE (workspace_id, crm_user_id)
);

CREATE TABLE crm_pipelines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Sales pipeline',
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, id)
);

CREATE UNIQUE INDEX crm_one_primary_pipeline_per_workspace
  ON crm_pipelines (workspace_id) WHERE is_primary;

CREATE TABLE crm_pipeline_stages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  pipeline_id UUID NOT NULL,
  name TEXT NOT NULL,
  stage_kind TEXT NOT NULL DEFAULT 'open' CHECK (stage_kind IN ('open', 'won', 'lost')),
  position NUMERIC(20, 8) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, pipeline_id)
    REFERENCES crm_pipelines(workspace_id, id) ON DELETE CASCADE
);

CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  sector TEXT,
  size SMALLINT,
  linkedin_url TEXT,
  website TEXT,
  phone_number TEXT,
  address TEXT,
  zipcode TEXT,
  city TEXT,
  state_abbr TEXT,
  sales_id BIGINT REFERENCES sales(id),
  context_links JSONB,
  country TEXT,
  description TEXT,
  revenue TEXT,
  tax_identifier TEXT,
  logo JSONB,
  UNIQUE (workspace_id, id)
);

CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  gender TEXT,
  title TEXT,
  background TEXT,
  avatar JSONB,
  first_seen TIMESTAMPTZ,
  last_seen TIMESTAMPTZ,
  has_newsletter BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT,
  tags BIGINT[] NOT NULL DEFAULT '{}',
  company_id BIGINT,
  sales_id BIGINT REFERENCES sales(id),
  linkedin_url TEXT,
  email_jsonb JSONB NOT NULL DEFAULT '[]'::JSONB,
  phone_jsonb JSONB NOT NULL DEFAULT '[]'::JSONB,
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, company_id)
    REFERENCES companies(workspace_id, id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE contact_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL,
  text TEXT,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sales_id BIGINT REFERENCES sales(id),
  status TEXT,
  attachments JSONB NOT NULL DEFAULT '[]'::JSONB,
  FOREIGN KEY (workspace_id, contact_id)
    REFERENCES contacts(workspace_id, id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  pipeline_id UUID NOT NULL,
  name TEXT NOT NULL,
  company_id BIGINT,
  contact_ids BIGINT[] NOT NULL DEFAULT '{}',
  category TEXT,
  stage UUID NOT NULL,
  description TEXT,
  amount BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at TIMESTAMPTZ,
  archived_by_user_id UUID REFERENCES crm_users(id) ON DELETE SET NULL,
  archived_stage_id UUID,
  archived_position NUMERIC(20, 8),
  expected_closing_date DATE,
  sales_id BIGINT REFERENCES sales(id),
  index NUMERIC(20, 8) NOT NULL DEFAULT 0,
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, pipeline_id)
    REFERENCES crm_pipelines(workspace_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (workspace_id, stage)
    REFERENCES crm_pipeline_stages(workspace_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (workspace_id, archived_stage_id)
    REFERENCES crm_pipeline_stages(workspace_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (workspace_id, company_id)
    REFERENCES companies(workspace_id, id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE deal_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  deal_id BIGINT NOT NULL,
  type TEXT,
  text TEXT,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sales_id BIGINT REFERENCES sales(id),
  attachments JSONB NOT NULL DEFAULT '[]'::JSONB,
  FOREIGN KEY (workspace_id, deal_id)
    REFERENCES deals(workspace_id, id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT NOT NULL
);

CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL,
  type TEXT,
  text TEXT,
  due_date TIMESTAMPTZ,
  done_date TIMESTAMPTZ,
  sales_id BIGINT REFERENCES sales(id),
  FOREIGN KEY (workspace_id, contact_id)
    REFERENCES contacts(workspace_id, id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE configuration (
  workspace_id UUID PRIMARY KEY REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  config JSONB NOT NULL DEFAULT '{}'::JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE crm_file_objects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  object_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  created_by_user_id UUID REFERENCES crm_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE crm_runtime_settings (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
  meta_title TEXT NOT NULL DEFAULT 'Holedo CRM',
  meta_description TEXT NOT NULL DEFAULT 'Track sales and customer conversations.',
  landing_headline TEXT NOT NULL DEFAULT 'Track sales and customer conversations',
  landing_subtitle TEXT NOT NULL DEFAULT 'Keep leads, deals and every customer conversation together in one clear workspace.',
  privacy_url TEXT NOT NULL DEFAULT 'https://www.iubenda.com/privacy-policy/84980546',
  cookie_url TEXT NOT NULL DEFAULT 'https://www.iubenda.com/privacy-policy/84980546/cookie-policy',
  terms_url TEXT NOT NULL DEFAULT 'https://www.iubenda.com/terms-and-conditions/84980546',
  imprint_url TEXT NOT NULL DEFAULT 'https://www.holedo.com/imprint/',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO crm_runtime_settings (id) VALUES (TRUE) ON CONFLICT (id) DO NOTHING;

CREATE TABLE crm_navigation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  url TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO crm_navigation (label, url, sort_order, enabled)
SELECT seed.label, seed.url, seed.sort_order, TRUE
FROM (VALUES ('CRM', '/', 0), ('Contacts', '/contacts', 10), ('Companies', '/companies', 20), ('Deals', '/deals', 30)) AS seed(label, url, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM crm_navigation);

CREATE TABLE crm_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES crm_workspaces(id) ON DELETE CASCADE,
  actor_user_id UUID REFERENCES crm_users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE VIEW companies_summary WITH (security_invoker = on) AS
SELECT c.*, count(DISTINCT d.id) AS nb_deals, count(DISTINCT co.id) AS nb_contacts
FROM companies c
LEFT JOIN deals d ON d.workspace_id = c.workspace_id AND d.company_id = c.id
LEFT JOIN contacts co ON co.workspace_id = c.workspace_id AND co.company_id = c.id
GROUP BY c.id;

CREATE OR REPLACE VIEW contacts_summary WITH (security_invoker = on) AS
SELECT co.*,
  jsonb_path_query_array(co.email_jsonb, '$[*]."email"')::TEXT AS email_fts,
  jsonb_path_query_array(co.phone_jsonb, '$[*]."number"')::TEXT AS phone_fts,
  c.name AS company_name,
  count(DISTINCT t.id) FILTER (WHERE t.done_date IS NULL) AS nb_tasks
FROM contacts co
LEFT JOIN tasks t ON t.workspace_id = co.workspace_id AND t.contact_id = co.id
LEFT JOIN companies c ON c.workspace_id = co.workspace_id AND c.id = co.company_id
GROUP BY co.id, c.name;

CREATE OR REPLACE VIEW activity_log WITH (security_invoker = on) AS
SELECT ('company.' || c.id || '.created') AS id, c.workspace_id,
  'company.created' AS type, c.created_at AS date, c.id AS company_id, c.sales_id,
  to_json(c.*) AS company, NULL::JSON AS contact, NULL::JSON AS deal,
  NULL::JSON AS contact_note, NULL::JSON AS deal_note
FROM companies c
UNION ALL
SELECT ('contact.' || co.id || '.created'), co.workspace_id,
  'contact.created', co.first_seen, co.company_id, co.sales_id,
  NULL::JSON, to_json(co.*), NULL::JSON, NULL::JSON, NULL::JSON
FROM contacts co
UNION ALL
SELECT ('contactNote.' || cn.id || '.created'), cn.workspace_id,
  'contactNote.created', cn.date, co.company_id, cn.sales_id,
  NULL::JSON, NULL::JSON, NULL::JSON, to_json(cn.*), NULL::JSON
FROM contact_notes cn JOIN contacts co ON co.workspace_id = cn.workspace_id AND co.id = cn.contact_id
UNION ALL
SELECT ('deal.' || d.id || '.created'), d.workspace_id,
  'deal.created', d.created_at, d.company_id, d.sales_id,
  NULL::JSON, NULL::JSON, to_json(d.*), NULL::JSON, NULL::JSON
FROM deals d
UNION ALL
SELECT ('dealNote.' || dn.id || '.created'), dn.workspace_id,
  'dealNote.created', dn.date, d.company_id, dn.sales_id,
  NULL::JSON, NULL::JSON, NULL::JSON, NULL::JSON, to_json(dn.*)
FROM deal_notes dn JOIN deals d ON d.workspace_id = dn.workspace_id AND d.id = dn.deal_id;

CREATE OR REPLACE FUNCTION crm_current_workspace_id() RETURNS UUID
LANGUAGE SQL STABLE AS $$
  SELECT NULLIF(current_setting('app.workspace_id', TRUE), '')::UUID
$$;

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'sales', 'crm_pipelines', 'crm_pipeline_stages', 'companies', 'contacts',
    'contact_notes', 'deals', 'deal_notes', 'tags', 'tasks', 'configuration',
    'crm_file_objects', 'crm_audit_events'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY workspace_isolation ON %I USING (workspace_id = crm_current_workspace_id()) WITH CHECK (workspace_id = crm_current_workspace_id())',
      table_name
    );
  END LOOP;
END $$;

CREATE INDEX companies_workspace_name_idx ON companies (workspace_id, name);
CREATE INDEX contacts_workspace_last_seen_idx ON contacts (workspace_id, last_seen DESC);
CREATE INDEX contact_notes_workspace_contact_idx ON contact_notes (workspace_id, contact_id, date DESC);
CREATE INDEX deals_workspace_stage_archive_position_idx ON deals (workspace_id, stage, archived_at, index);
CREATE INDEX deal_notes_workspace_deal_idx ON deal_notes (workspace_id, deal_id, date DESC);
CREATE INDEX tasks_workspace_contact_due_idx ON tasks (workspace_id, contact_id, due_date);
CREATE INDEX file_objects_workspace_created_idx ON crm_file_objects (workspace_id, created_at DESC);
CREATE INDEX audit_events_workspace_created_idx ON crm_audit_events (workspace_id, created_at DESC);
