ALTER TABLE crm_runtime_settings
  ADD COLUMN IF NOT EXISTS accent_color TEXT NOT NULL DEFAULT '#32a3fd',
  ADD COLUMN IF NOT EXISTS site_icon_url TEXT NOT NULL DEFAULT '/assets/branding/1gc-holedo-icon-for-dark-bg.png',
  ADD COLUMN IF NOT EXISTS og_image_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS login_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS signup_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_button_text TEXT NOT NULL DEFAULT 'Start Now',
  ADD COLUMN IF NOT EXISTS hero_button_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS head_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_code TEXT NOT NULL DEFAULT '';
